package com.nab.icommerce.products.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

@DynamoDBTable(tableName = "iCommerce-Products")
public class Product {
    @Getter
    @Setter
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String uuid;

    @Getter
    @Setter
    @DynamoDBAttribute
    private String name;

    @Getter
    @Setter
    @DynamoDBAttribute
    private String imagePath;

    @Getter
    @Setter
    private String category;

    @Getter
    @Setter
    @DynamoDBAttribute
    private double price;

    @Getter
    @Setter
    @DynamoDBAttribute
    private String brand;

    @Getter
    @Setter
    @DynamoDBAttribute
    private String colour;
}
